### ISSUE TITLE
no audio devices anymore

### ISSUE THREAD

**Issue by deprale** [devangshekhawat/Fedora-40-Post-Install-Guide#12]
I have no audio after running your proper media callback section, I'm on fedora 40 KDE.

**Comment by devangshekhawat** [comment]
I cannot pinpoint exactly what might have caused it on your end. I will keep the issue open for a while until someone else encounters it again so that we can know whether it is a problem in the guide or in your system itself.

**Comment by devangshekhawat** [comment]
closing because of no response

**Comment by Asion001** [comment]
@devangshekhawat   The same, only dummy device probably after media commands
<img width="1030" height="690" alt="Image" src="https://github.com/user-attachments/assets/736aac62-f35f-42c2-9fd9-39b375dca695" />

**Comment by devangshekhawat** [comment]
@Asion001 I might be asking the obvious, but did you try rebooting your system? Should most likely fix this, since to me this looks like a pipewire issue.

**Comment by Asion001** [comment]
Yes i did try to reboot and it was still the same. I reinstalled again and it's looks like not after media command's but after Nvidia driver. Now I'm trying to reinstall and wait for modules to build.

**Comment by devangshekhawat** [comment]
Very interesting, did it work in your second attempt with the nvidia drivers?

**Comment by Asion001** [comment]
Sorry for late response, it did not. 
Today i installed v44 release, without disk encryption and without secure boot. Updated all packages from store, rebooted, installed nvidia drivers from store, rebooted, and ran repos, flatpak, appimage and multimedia commands. Now its working fine. 
So it could be v44 beta version problem or maybe disk encryption. 

<details><summary>PC specs for context</summary>
<p>

``` bash
> inxi -F

System:
  Host: DESKTOP.lan Kernel: 6.19.14-300.fc44.x86_64 arch: x86_64
    bits: 64
  Desktop: GNOME v: 50.1 Distro: Fedora Linux 44 (Workstation Edition)
Machine:
  Type: Desktop System: ASUS product: N/A v: N/A serial: <superuser required>
  Mobo: ASUSTeK model: ROG STRIX B850-I GAMING WIFI v: Rev 1.xx
    serial: <superuser required> Firmware: UEFI vendor: American Megatrends
    v: 1644 date: 03/10/2026
CPU:
  Info: 8-core model: AMD Ryzen 7 9700X bits: 64 type: MT MCP cache: L2: 8 MiB
  Speed (MHz): avg: 605 min/max: 605/5582 cores: 1: 605 2: 605 3: 605 4: 605
    5: 605 6: 605 7: 605 8: 605 9: 605 10: 605 11: 605 12: 605 13: 605 14: 605
    15: 605 16: 605
Graphics:
  Device-1: NVIDIA GB205 [GeForce RTX 5070] driver: nvidia v: 595.58.03
  Device-2: Advanced Micro Devices [AMD/ATI] Granite Ridge [Radeon Graphics]
    driver: amdgpu v: kernel
  Display: wayland server: X.Org v: 24.1.11 with: Xwayland v: 24.1.11
    compositor: gnome-shell driver: gpu: nv_platform,nvidia,nvidia-nvswitch
    resolution: 2560x1440~280Hz
  API: OpenGL v: 4.6.0 vendor: nvidia v: 595.58.03 renderer: NVIDIA GeForce
    RTX 5070/PCIe/SSE2
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
  Info: Tools: api: glxinfo gpu: nvidia-settings x11: xdriinfo, xdpyinfo,
    xprop, xrandr
Audio:
  Device-1: NVIDIA GB205 High Definition Audio driver: snd_hda_intel
  Device-2: Advanced Micro Devices [AMD/ATI] Radeon High Definition Audio
    driver: snd_hda_intel
  Device-3: fifine Microphone driver: hid-generic,snd-usb-audio,usbhid
    type: USB
  Device-4: ASUSTek USB Audio driver: hid-generic,snd-usb-audio,usbhid
    type: USB
  API: ALSA v: k6.19.14-300.fc44.x86_64 status: kernel-api
  Server-1: PipeWire v: 1.6.4 status: active
Network:
  Device-1: Intel Ethernet I226-V driver: igc
  IF: eno1 state: up speed: 2500 Mbps duplex: full mac: bc:fc:e7:ea:5e:6b
  Device-2: MEDIATEK MT7925 802.11be 160MHz 2x2 PCIe Wireless Network
    Adapter [Filogic 360] driver: mt7925e
``` 

</p>
</details>

**Comment by devangshekhawat** [comment]
Disk encryption + secure boot might very likely have been the issues since you also installed nvidia drivers. Check the main guide for the new changes, there are extra steps if you have secure boot enabled + even more steps if you have encrypted drives.
