### ISSUE TITLE
Include : Open ports when GSConnect is not visible even in the same network

### ISSUE THREAD

**Issue by aswinbennyofficial** [devangshekhawat/Fedora-40-Post-Install-Guide#23]
I think this would be a common issue for the users that install GSConnect for the first time :
`I have two devices running KDE Connect on the same network, but they can't see each other`

```
sudo firewall-cmd --permanent --zone=public --add-service=kdeconnect
sudo firewall-cmd --reload
```
source : https://userbase.kde.org/KDEConnect#firewalld

**Comment by devangshekhawat** [comment]
Done
